name: Infracost analysis (directory)

on:
  push:
    branches: [ "master" ]
    paths:
      - "**.tf"
      - "**.hcl"
      - "**.tfstate"
      - "**.tfstate.backup"
      - "**.tfvars"
      - ".github/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "**.tf"
      - "**.hcl"
      - "**.tfstate"
      - "**.tfstate.backup"
      - "**.tfvars"
      - ".github/**"
  workflow_dispatch:      # Allows you to manually trigger the workflow

env:
  TF_WORKING_DIR: infra

permissions:
  contents: read
  pull-requests: write

jobs:
  infracost:
    name: infracost
    runs-on: ubuntu-latest

    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      # github.event.pull_request.base.ref returns null when no present pull_request (eg. when triggered manually), and the checkout defaults to the default/main branch

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline (JSON)
        run: |
          infracost breakdown --path=${{ env.TF_WORKING_DIR }} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      - name: Upload Infracost baseline as artifact
        uses: actions/upload-artifact@v4
        with:
          name: infracost-base-json
          path: /tmp/infracost-base.json

      - name: Generate Infracost cost estimate baseline (HTML)
        if: ${{ !github.event.pull_request }}
        run: |
          infracost breakdown --path=${{ env.TF_WORKING_DIR }} \
                              --format=html \
                              --out-file=/tmp/infracost-base.html

      - name: Upload Infracost baseline as artifact
        if: ${{ !github.event.pull_request }}
        uses: actions/upload-artifact@v4
        with:
          name: infracost-base-html
          path: /tmp/infracost-base.html


      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        if: ${{ github.event.pull_request }}
        uses: actions/checkout@v4

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        if: ${{ github.event.pull_request }}
        run: |
          infracost diff --path=${{ env.TF_WORKING_DIR }} \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
                          
      - name: Post Infracost comment
        if: ${{ github.event.pull_request }}
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                      --repo=$GITHUB_REPOSITORY \
                                      --github-token=${{github.token}} \
                                      --pull-request=${{github.event.pull_request.number}} \
                                      --behavior=update
