name: Terraform analysis

on:
  push:
    branches: [ "master" ]
    # paths:
    #   - "**.tf"
    #   - "**.hcl"
    #   - "**.tfstate"
    #   - "**.tfstate.backup"
    #   - "**.tfvars"
    #   - ".github/**"
  pull_request: 
    branches: [ "master" ]
    # paths:
    #   - "**.tf"
    #   - "**.hcl"
    #   - "**.tfstate"
    #   - "**.tfstate.backup"
    #   - "**.tfvars"
    #   - ".github/**"
  workflow_dispatch:      # Allows you to manually trigger the workflow

env:
  TF_WORKING_DIR: infra

permissions:
  security-events: write


jobs:
  tf-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - run: echo "HASHABLE_DEPENDENCIES_PATH=${{ env.TF_WORKING_DIR }}/.tflint.hcl" >> $GITHUB_ENV

      - name: Cache plugin dir
        uses: actions/cache@v4    # This action allows caching dependencies and build outputs to improve workflow execution time.
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles( env.HASHABLE_DEPENDENCIES_PATH ) }}  # Using the hashFiles function allows you to create a new cache when dependencies change.
  
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
            tflint_wrapper: true
  
      - name: Init TFLint
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
      - name: Run TFLint
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tflint -f compact --recursive

  tf-security-scan:
    # Tfsec is included in trivy
    name: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Vulnerability scan with Trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          # Configured to scan infrastructure-as-code (IaC) files
          scan-type: 'config'
          hide-progress: true
          # Generates results in SARIF (a standardized format that integrates well with GitHub’s Security tab)
          format: 'sarif'
          output: 'trivy-results.sarif'
          # Setting it to '1' ensures that the action fails if it finds issues at these levels, which is useful for CI/CD enforcement.
          exit-code: '1'
          # Reduces clutter by skipping issues that don’t yet have fixes.
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
      # With the following "if" you can run a github action step even if the previous step fails. You can add "always()", but if you don't want  If you don't want the function to run when you manually cancel a job, write:
        if: failure() || success()
        uses: github/codeql-action/upload-sarif@v3
        # The results from the other step will appear in GitHub’s Security tab.
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Vulnerability scan with Checkov
        if: failure() || success()
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.TF_WORKING_DIR }}
          download_external_modules: true
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
        
      - name: Upload Checkov scan results to GitHub Security tab
        if: failure() || success()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif

      # # Step 7: Run Infracost (cost estimation)
      # - name: Run Infracost
      #   working-directory: infra
      #   run: |
      #     infracost breakdown --format json > infracost_output.json
      #     infracost show --path infracost_output.json --format table
